name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Generate changelog
        run: |
          git fetch --tags
          last_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo $(git rev-list --max-parents=0 HEAD))
          git log $last_tag..HEAD --pretty=format:"%h - %s (%an)" > CHANGELOG.md

      - name: Build artifact
        run: python setup.py sdist bdist_wheel

      - name: Upload release to GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            See the changelog for details:
            ```markdown
            $(cat CHANGELOG.md)
            ```
